### ISSUE TITLE
Fatal error after installation

### ISSUE THREAD

**Issue by theBAY84** [umdevelopera/um-polylang#7]
Hey!

When I am installing your plugin on my Website X it causes a fatal error (see Screenshot). Do you know what causes the error?

On all my other websites your plugin works fine and is very excellent. I only get this fatal error on Website X.  Any idea what went wrong here?

Best regards

Sebastian
![Screenshot 1 (Fatal Error)](https://github.com/umdevelopera/um-polylang/assets/96189274/2aaa366f-f104-4fe2-883e-f98bdcb8877a)

**Comment by umdevelopera** [comment]
Download the latest version and re-install the extension. The plugin folder must be `um-polylang`, not `um-polylang-main`.

Verify that the default language in the Polylang settings is set properly.
![default language](https://github.com/user-attachments/assets/177fe091-f996-46ea-8421-8d178c4731cf)
