### ISSUE TITLE
can't translate default strings

### ISSUE THREAD

**Issue by wpdevlife** [umdevelopera/um-polylang#8]
How to translate strings in default pages such as this one below ? 

![image](https://github.com/umdevelopera/um-polylang/assets/162557962/d039fa3c-44d9-4db4-a3a1-34cddb9a89a7)

**Comment by umdevelopera** [comment]
The question is not related to this extension.
Use the [Poedit](https://poedit.net/download) program or the [Loco Translate](https://wordpress.org/plugins/loco-translate/) plugin to edit strings in the language files.
Follow instructions in the article [How to translate plugin](https://docs.ultimatemember.com/article/1449-how-to-translate-plugin).
